### ISSUE TITLE
Multilingual interface

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#115]
Select language in menu.

Languages:

- Englisch
- Deutsch

All terminology used for application UI shall be available in editable text files.

**Comment by annikabock** [comment]
done with #334

**Comment by imsk111** [comment]
Bitte noch die anderen Sprachen (SE, LV, DK, ES) hinzufügen.

Wäre es möglich diese Infos auch erst während der Laufzeit zu laden, so dass die Dateien im Storage abgelegt und nachträglich geändert werden können?

**Comment by annikabock** [comment]
@imsk111 ich kopiere deinen Kommentar mal in das aktuelle Ticket, dieses hier ist bereits geschlossen und erledigt
