### ISSUE TITLE
Add einwohnerzahlen to legende

### ISSUE THREAD

**Issue by annikabock** [ANN-RADAR/ann-radar-prototype#338]

**Comment by imsk111** [comment]
@andreashelms leider werden diese Zahlen jetzt nicht merh angetzeigt. Könnte ihr da bitte nochmal reinschauen?

**Comment by andreashelms** [comment]
Die Projektion der `HH_Baubloecke_Netto.geojson` sowie der property name für die Baublöcke haben sich geändert, daher konnte die Berechnung nicht mehr ausgeführt werden. Ich habe das im Code entsprechend angepasst.
