### ISSUE TITLE
What's left over?

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#354]
1. Auf der Ebene City werden keine Daten in der Tabelle rechts angezeigt (Bug) -- #359 
2. Austausch/Update Daten zu den jeweiligen Layern -> nn.json durch einfaches Austauschen der Datei im Google Storage und nicht im Source Code (war vereinbart) -- #358 
3. Reihenfolge und Anzeige der Parameter in der Tabelle über "potential_config.json" -> Reihenfolge wird nicht wie erwartet geändert, grundsätzlich funktioniert es aber (Bug?). Eine Herausforderung ist, dass irgendein "Caching" außerhalb des Browsers stattfindet, so dass die Änderungen nicht sofort sichtbar werde, d.h. das Testen ist etwas langwierig.
4. Solar Coverage Rate lädt in der jetzigen Version anscheinend garnicht mehr (auch wenn man lange wartet > 10 Minuten) --> #361 
5. Ansicht Verwaltungsgrenzen als oberster Layer (nice to have)
6. Legenden zu einigen Ansichten fehlen (nice to have)

**Comment by annikabock** [comment]
@imsk111 zu Punkt 3 bräuchte ich noch Infos, wenn es nicht funktioniert. Ansonsten sind die letzten beauftragten Dinge erledigt

**Comment by imsk111** [comment]
Punkt 3 läuft. Es braucht aus irgendeinem Grund wohl manchmal etwas länger, bis es in der aktuellen Ansicht auftaucht. Ist damit erledigt. 🙂

**Comment by annikabock** [comment]
Klasse, danke!
