### ISSUE TITLE
Solar coverage rate and potetnial of renovation at building block level do not show

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#361]

**Comment by annikabock** [comment]
Hi @imsk111 

Das scheint wieder irgendwas mit der Projektion zu sein. Eigentlich sollte openlayers das konvertieren können, aber klappt irgendwie nicht. Wir bekommen leider auch keinen Fehler angezeigt. Leslie hat auch schon openlayers geupdated, aber das hat nicht geholfen. 

Wäre es für dich @frankRogge wäre es für dich möglich [diese Datei]((https://storage.googleapis.com/ann-radar-data/HH_Baubloecke_Netto.geojson)) noch einmal in einer passenden Projektion zu liefern. Die aktuelle Projektion der Daten ist EPSG:25832 und wir brauchen EPSG:3857.

**Comment by FrankRogge** [comment]
Danke für den Hinweis. Stimmt. Das wurde nur als "json-file mit  
Geometry" gespeichert.
Habe das nochmal ins GeoJson geschrieben. Nun sollte es passen.

https://drive.google.com/file/d/19XuX_KcQGfqPr6onMiw17xBe9KthiCW1/view?usp=share_link
Message ID: ***@***.***>
Gruß
Frank

**Comment by annikabock** [comment]
Hi @FrankRogge hast du Leslies Anmerkung/Anfrage schon gesehen?

---

cc @imsk111

**Comment by FrankRogge** [comment]
Hallo Annika,
meinst Du die Anmerkung vom 10.1.?
  /Am 10.01.2023 um 10:56 schrieb Leslie Lawendel:/

  ***@***.***[1] Wir haben den Fehler gefunden. In den Properties  
müsste es, analog zu den Kartenlayern vom Geoportal, eine Property  
"baublockbezeichnung" geben. Diese heißt in deiner GeoJSON "BBZ".  
Könntest du das bitte umbenennen?/

   

  Ja, wurde am 11.1. beantwortet, bzw. ich habe in den BB-Layer die  
Attributbezeichnungen geändert.
/anbei die Baubblocklayer mit neuer Attributsbezeichung (BBZ zu  
baublockbezeichnung)/

  /Feature-Layer
https://drive.google.com/file/d/19XuX_KcQGfqPr6onMiw17xBe9KthiCW1/view?usp=share_link/

  /Datenlayer
https://drive.google.com/file/d/1OpSawzuEf-2o3s-Gm6iHnrEi144A2Rfj/view?usp=share_link/

   
  Am 10.01.2023 um 10:56 schrieb Leslie Lawendel:

  @FrankRogge[1] Wir haben den Fehler gefunden. In den Properties  
müsste es, analog zu den Kartenlayern vom Geoportal, eine Property  
"baublockbezeichnung" geben. Diese heißt in deiner GeoJSON "BBZ".  
Könntest du das bitte umbenennen?
 



Zitat von annikabock ***@***.***>:

>  
>
>   Hi @FrankRogge[1] hast du Leslies Anmerkung/Anfrage schon gesehen?
>
> -------------------------
>
>   cc @imsk111[2]
>
>   —
> Reply to this email directly, view it on GitHub[3], or unsubscribe[4].
> You are receiving this because you were mentioned.Message ID:  
> ***@***.***>



Links:
------
[1] https://github.com/FrankRogge
[2] https://github.com/imsk111
[3]  
https://github.com/ANN-RADAR/ann-radar-prototype/issues/361#issuecomment-1384003924
[4]
