### ISSUE TITLE
Visualisation of table data

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#365]
To improve data exploration a visual representation of key data should be added to the right side of the panel.

It could extract selected data from the table and display it as a bar graph (others may follow later).

The data coloumn to display should be selectable. (maybe later the type of visualisation).

**Comment by annikabock** [comment]
Should this automatically be shown, when map is hiffen? Or should the user have the possibility to select the extracted data from all possible data?

@imsk111

**Comment by imsk111** [comment]
A little more detail (with opportunities for suggestions):

1. It sounds like a good idea to show this only, when the map is hidden due to space restrictions with map shown, yes.
2. The selection of the data may happen by marking a coloumn of the data shown in the table (so only the selcted data)
3. We could start with just a bar chart / histogram, since the data maps to discrete entities
4. Ideally this should follow the sequence of the rows shown in the table, meaning it can be rearranged by clicking on any of the coloums in the table, since this changes the order of the rows in the table (current functionality already implemented).

**Comment by annikabock** [comment]
@imsk111 Wäre es eine Idee einen Toggle einzubauen, der map und chart austauscht und wir dann analog zu der tabelle auf der rechten Seite auch links ein Dropdown anbieten, wo die Kennzahlen aus der Tabelle rechts verfügbar sind. Dann zusätzlich eine Auswahl des Diagrammtyps?

Was meinst du dazu?

**Comment by imsk111** [comment]
Toggle + swap sounds good ...

Die Auswahl des Diagrammtyps kann gern über ein Dropdown erfolgen. Ich denke nur, dass wir mit einem Barchart erstmal gut bedinet sind, da die Informationen immer diskreten Einheiten (Building Blocks, Districts) zugeordnet sind. Weitere Diagrammtypen wären dann eine Option für später. Gut wäre zusätzlich noch, wenn die Reihenfolge der Reihenfolge der Zeilen in der Tabelle folgt. So könnten wir einfach nach bestimmten Parmatern sortieren.

**Comment by annikabock** [comment]
Also die Empfehlung ist, in en TabellenHeader zusätzlich zum Sortierungspfeil ein Icon einzublenden, mit dem das Diagramm angezeigt wird. Die Karte würden wir dann nur auf diese Aktion hin ausblenden, um weniger Klicks zu produzieren.

Initial wird eine Barchart angeboten. 

Issue #366 würde dann nicht benötigt.
