### ISSUE TITLE
Display additional information for layer elements (e.g. tree size, diameter, type, age)

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#368]
Display additional information for layers (e.g. street trees -> height, diameter, age).

**Comment by annikabock** [comment]
@imsk111 where do we get this data from? Geoportal or Franks data?

**Comment by imsk111** [comment]
In the first place geoportal: e.g. street trees 

https://www.hamburg.de/strassenbaeume-online-karte/
https://metaver.de/trefferanzeige?cmd=doShowDocument&docuuid=C1C61928-C602-4E37-AF31-2D23901E2540



![Image](https://user-images.githubusercontent.com/16405757/221365867-d8d32ed8-c2ff-4ee1-a025-51a5b4dbb2cd.png)

**Comment by annikabock** [comment]
Hi @imsk111 also wenn ich es gänzlich richtig verstehe dann sind das zwei Punkte

1. weitere Layer anzeigen wie ZB Bäume aus dem Geoportal
2. Einzelne Elemente klickbar machen und ein Infowindow mit mehr Informationen anzeigen

Ist das richtig?
Wenn ja dann ist der zweite Punkt sehr komplex, weniger in der Implementierung aber weil wir uns da etwas einfallen lassen müssen, wie wir diese Kikcbar machen, ohne dass der Klick mit der Area Auswahl in den Konflikt kommt und dennoch intuitiv ist, dass man dies klicken kann.
Zusätzlich haben wir ja die Möglichkeit mehrere Layer anzuzeigen, die sich überlagern - also beispielsweise Solar Potential und Social Monitoring - das ist für das Auge nachvollziehbar aber hier liegt Solar Potential unter dem anderen so dass dort diese Elemente nicht ansteuerbar sind, weil sie einfach drunter liegen. Das kann uns bei den Bäumen auch passieren - oder aber wir setzen sie im z-index nach oben aber dann würden diese ggf. andere Kennzahlen oder Elemente überlagern. 
Es wird zusätzlich einfach nicht unbedingt ersichtlich sein, welcher Layer der oberste ist und so weiter
Der Aufwand hier würde von dem Konzept dazu abhängen und ehrlich gesagt mangelt es uns da an spontanen Ideen. Darüber müssten wir uns genauere Gedanken machen - auch mit euch zusammen, um entsprechende Entscheidungen zu fällen

**Comment by annikabock** [comment]
- wir würden das Infowindow on Hover einblenden. Diese Aktion haben wir bisher noch nicht belegt. 
- Styling des Infowindows
- Einbinden der Layer und Abfragen der Properties

Annahme: Das Einbinden der Layer funktioniert wie bereits bei anderen Layern aus dem Geoportal bekannt

**Comment by imsk111** [comment]
passt so, würde aber auch nur für den obersten Layer funktionieren, oder?

**Comment by annikabock** [comment]
Ja und Nein, es kommt ein bisschen darauf an, wie die Layer getrickt sind, wenn es sich um Punktdaten handelt, wie ggf bei Bäumen, dann kommt man in den Zwischenräumen sicher dazwischen, aber generell würde ich da zu JA tendieren

**Comment by annikabock** [comment]
Gemäß Beauftragung bitte für die folgenden Layer umsetzen:

- [ ] Solarpotential (je Gebäude)
- [ ] Primärenergie (je Gebäude), 
- [ ] Building and Living (je POI), 
- [ ] Social Infrastructure (je POI)

**Comment by annikabock** [comment]
offene Fragen:

- In der Beauftragung sind die 4 oben genannten Layer aufgezählt. Weiter oben im Ticket steht aber noch was von einem Street Tree Layer. Den könnten wir noch zusätzlich zu den 4 anderen im Budget unterbringen, wenn ihr das für sinnvoll erachtet?
- Könntet ihr uns bitte die Geoportal Links zu den Layern teilen, damit wir sicher die richtigen verbauen?
Gerne als Kommentar in diesem Issue

**Comment by imsk111** [comment]
Bitte Straßenbäume hinzufügen

**Comment by annikabock** [comment]
Hi @imsk111 
die Links sind im vorangegangenen Kommentar leider nicht angekommen. Könntest du die bitte noch ergänzen?

**Comment by imsk111** [comment]
Ist noch nicht fertiggestellt. Frank ergänzt diese.

**Comment by FrankRogge** [comment]
Solarpotential: nur der WMS-Dienst verfügbar, welcher bereits im Tool integriert ist. 
Die Gebäudedaten wurden per "Webcrawler" automatisiert für jedes (Wohn-)Gebäude abgerufen. Den Datensatz habe ich lokal vorliegen.
Strassenbaumkataster:
xlink:href="https://geodienste.hamburg.de/HH_WFS_Strassenbaumkataster?"
Primärenergie Gebäude:
href="https://geodienste.hamburg.de/HH_WFS_Waermekataster_Waermebedarf?"
"Spezifischer Wärmebedarf unsaniert" und "Spezifischer Wärmebedarf saniert" liefert dann für Wohngebäude die Werte.

Für "building and living" und "Social infrastructure" muß ich nachliefern. Das "GeoOnline" ermöglicht derzeit keine Suche, daher muß ich über Metaver recherchieren. Da finde ich über die (deutschen) Begriffe keine passenden Datensätze.

**Comment by annikabock** [comment]
Zusammenfassung aus dem Meeting mit Frank:

- Frank liefert uns für den Layer Solarpotential im Laufe der KW35 ein zusammengeführtes JSON file, das wir dann integrieren können
- Straßenbaumkataster nehmen wir als Base Layer mit auf. Die Punkte werden mit entsprechendem Kronendurchmesser abgebildet
- Für Primärenergie Gebäude ist der Link da und wir können diesen Nutzen. Die beiden Werte spezifischer Wärembedarf unsaniert und saniert werden im Infowindow einfach nebeneinander angezeigt

- für building and living sowie für social infrastructure benötigen wir die Links zum Geoportal nicht erneut. Die Layer haben wir bereits eingebaut und rufen nun zusätzlich die entsprechenden Details/Attribute im Infowindow an. 
Aktuell haben wir dort folgende Layer kombiniert
Social Infrastructure:
HH_WMS_Freiwilliges_Engagement
HH_WMS_Familien_Angebote
HH_WMS_Sozialraeumliche_Angebote_der_Jugend-_und_Familienhilfe
HH_WMS_Jugend_Aktiv_Plus
HH_WMS_KitaEinrichtung

Building and Living:
HH_WMS_Wohnungsbauprojekte
HH_WMS_Wohnbauflaechenpotenziale

**Comment by annikabock** [comment]
@imsk111 
Wir können bei den Tile Layern hier die Info Windows nicht on hover zeigen, das geht nur sinnvoll bei Vector Layern, da man bei Tile Layern für jede Position nen API Request feuern muss. On hover wären das unendlich viele Requests wenn man sich über die Karte bewegt. Am besten zeigt man die Info Windows also on click, aber on click passieren bereits andere Dinge auf der Karte (z.B. Admin Area an- / abwählen). Wie wollen wir damit umgehen?
Das betrifft "Social Infrastructure" und "Building and Living".Wir haben da drauf herum gedacht, aber haben keine schlaue Idee. Hast du einen Wunsch?

**Comment by annikabock** [comment]
auch, wenn es nicht wirklcih die schönste Lösung ist, nehmen wir bitte den rechts-Klick. Danke

**Comment by plumdumpling** [comment]
Der Straßenbaumkataster als WFS (Vektor) Layer ist sehr groß (> 400 MB), was zu Performanceproblemen führt, weshalb ich stattdessen die entsprechenden WMS (Tile) Layer `strassenbaum` (Straßenbaumkataster Hamburg) und `strassenbaum_hpa` (Straßenbaumkataster Hamburger Hafen) eingebunden habe. Dieser kann auf allen Zoomstufen ohne Probleme dargestellt werden. Die Bäume werden dort auf höheren Zoomstufen auch mit entsprechendem Kronendurchmesser abgebildet, auf niedrigeren Zoomstufen in gleicher Größe, so dass sie noch gut erkennbar und klickbar sind. Die Info Windows der Bäume lassen sich wie bei "Social Infrastructure" und "Building and Living" per Rechtsklick öffnen.

**Comment by plumdumpling** [comment]
Wie Frank R. bereits vermutet hatte, lassen sich die beiden Layer zum Wärmebedarf (unsaniert und saniert) nicht kombinieren. Wir werden also nicht ein Info Window mit beiden Werten haben, sondern zwei getrennte Layer in der Anwendung.

Da der Layer "Spezifischer Wärmebedarf unsaniert" schon als WMS (Tile) Layer in der Anwendung vorhanden ist, habe ich ich diesen wie bereits vorhanden genutzt und Optionen für "saniert" und "unsaniert" (Radio Buttons als Unterpunkte für "Spezifischer Wärmebedarf") hinzugefügt. Die Info Windows lassen sich auch hier per Rechtsklick öffnen.

**Comment by FrankRogge** [comment]
Die konvertierten Layer für das Strassenbaumkataster liegen auf dem Google-Drive unter "RAW/Input_Frank". https://drive.google.com/drive/folders/1g7Y_Sl8iPa9zlfeG8mgUqoAXpkRmP_hH
Es sind, wie in der Quelldatei, 2 Geojson. Reguläres Kataster und Hafenbereich (_hpa). Projektion ist EPSG 4326.
Die Hauptdatei ist natürlich sehr groß (169MB).  Ich habe erstmal alle Metadaten im Export gelassen. Falls das Handling aufgrund der Größe damit zu schwer ist, kann ich auch nicht ganz so wichtige oder doppelte Attribute entfernen.

**Comment by FrankRogge** [comment]
Geojson der" HH Gebäude mit Wohnen und Solarpotential 2015"(p_st_mwha).
https://drive.google.com/drive/folders/1g7Y_Sl8iPa9zlfeG8mgUqoAXpkRmP_hH
Auch diese Datei ist recht groß. Falls notwendig, würde ich die Anzahl der Attribute reduzieren.  Ein paar Attribute sind nicht unbedingt für die Gebäudeinfo notwendig

**Comment by imsk111** [comment]
Moin zusammen, Frank und ich haben gerade die Funktion des Infofensters ausprobiert und folgende Überlegungen:

1. Das Fenster ist recht schmal und die Zeilen brechen ungünstig um. Können wir das Fenster auf 1,5/2-fache Breite bringen, damit es besser lesbar ist und ggf. die Schriftgröße um eine Stufe reduzieren?
2. Das Fenster ist jetzt fixiert und hängt an dem Objekt. Es wäre ggf. besser, wenn es wie im Geoportal gehandhabt wird und das Fenster initial rechts oben erscheint und man es dann verschieben könnte, damit man verdeckte Objekte hervorholen kann.
3. Beim Solarpotential haben wir noch das Hover-Window. Das ist sehr ungünstig, wenn sehr viele Gebäude nebeneinander liegen. Daher bitte für alle Pop-Up Windows den Rechtsklick verwenden.
4. Wir möchten gern noch die Objektdaten nachträglich ändern. Nach unserem Verständnis liegen auch die MVTs in diesem Ordner im Storage Bucket. Wo finden sich diese für die Straßenbäume?

**Comment by plumdumpling** [comment]
> 1. Das Fenster ist recht schmal und die Zeilen brechen ungünstig um. Können wir das Fenster auf 1,5/2-fache Breite bringen, damit es besser lesbar ist und ggf. die Schriftgröße um eine Stufe reduzieren?

Wir können die Properties in zwei Spalten darstellen und die Schriftgröße reduzieren.

> 2. Das Fenster ist jetzt fixiert und hängt an dem Objekt. Es wäre ggf. besser, wenn es wie im Geoportal gehandhabt wird und das Fenster initial rechts oben erscheint und man es dann verschieben könnte, damit man verdeckte Objekte hervorholen kann.

Das Fenster als fixes Overlay in der Ecke anzuzeigen ist kein Problem, aber das Verschieben des Fensters ist aufwändiger, da müssen wir schauen wie das noch ins Budget passt.

> 3. Beim Solarpotential haben wir noch das Hover-Window. Das ist sehr ungünstig, wenn sehr viele Gebäude nebeneinander liegen. Daher bitte für alle Pop-Up Windows den Rechtsklick verwenden.

Kein Problem, können wir auf Rechtsklick wie bei den anderen Layern legen.

> 4. Wir möchten gern noch die Objektdaten nachträglich ändern. Nach unserem Verständnis liegen auch die MVTs in diesem Ordner im Storage Bucket. Wo finden sich diese für die Straßenbäume?

Die Daten zum Straßenbaumkataster kommen vom Geoportal (https://github.com/ANN-RADAR/ann-radar-prototype/issues/368#issuecomment-1685921417). Wenn ihr dazu eigene Daten habt, müssten wir den Layer nochmal umbauen und brauchen die Daten dann entsprechend wieder als MVTs wie z.B. beim Solarpotential.

**Comment by andreashelms** [comment]
> > 1. Das Fenster ist recht schmal und die Zeilen brechen ungünstig um. Können wir das Fenster auf 1,5/2-fache Breite bringen, damit es besser lesbar ist und ggf. die Schriftgröße um eine Stufe reduzieren?
> 
> Wir können die Properties in zwei Spalten darstellen und die Schriftgröße reduzieren.
> 
> > 2. Das Fenster ist jetzt fixiert und hängt an dem Objekt. Es wäre ggf. besser, wenn es wie im Geoportal gehandhabt wird und das Fenster initial rechts oben erscheint und man es dann verschieben könnte, damit man verdeckte Objekte hervorholen kann.
> 
> Das Fenster als fixes Overlay in der Ecke anzuzeigen ist kein Problem, aber das Verschieben des Fensters ist aufwändiger, da müssen wir schauen wie das noch ins Budget passt.
> 
> > 3. Beim Solarpotential haben wir noch das Hover-Window. Das ist sehr ungünstig, wenn sehr viele Gebäude nebeneinander liegen. Daher bitte für alle Pop-Up Windows den Rechtsklick verwenden.
> 
> Kein Problem, können wir auf Rechtsklick wie bei den anderen Layern legen.
> 
> > 4. Wir möchten gern noch die Objektdaten nachträglich ändern. Nach unserem Verständnis liegen auch die MVTs in diesem Ordner im Storage Bucket. Wo finden sich diese für die Straßenbäume?
> 
> Die Daten zum Straßenbaumkataster kommen vom Geoportal ([#368 (comment)](https://github.com/ANN-RADAR/ann-radar-prototype/issues/368#issuecomment-1685921417)). Wenn ihr dazu eigene Daten habt, müssten wir den Layer nochmal umbauen und brauchen die Daten dann entsprechend wieder als MVTs wie z.B. beim Solarpotential.

@imsk111  Leslie hat die Punkte 1 + 3 bereits umgesetzt. Wie sieht es mit den offenen Punkten 2 + 4 aus? Ist die Umsetzung den Anmerkungen von Leslie entsprechend gewünscht?

**Comment by imsk111** [comment]
Sieht soweit gut aus, die Frage nach den Straßenbäumen war fehlgeleitet, es geht natürlich die selbsterstellten Layer. Soweit die alle für uns während der Laufzeit änderbar sind, passt es.

**Comment by annikabock** [comment]
@imsk111 

Zu 2. EinVerschieben wäre zu aufwendig in der Tat. Möchtest du es dann oben fixiert haben, oder bleibt es so wie es ist?

Zu 4. ich verstehe die Antwort nicht ganz - ist es so wie es ist für dich dann in Ordnung?

**Comment by annikabock** [comment]
wir fixieren das infowindow links oben an der map

@andreashelms
