### ISSUE TITLE
Free form selection of area to investigate

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#369]
Allow free form selection of area of interest to investigate and annotate the selected area.

**Comment by annikabock** [comment]
@imsk111 could you explain a bit more, what is your wish please. I am not sure if I understand the desire :)

**Comment by imsk111** [comment]
It would be good to beable to select or deselect a number of smaller units like Building Blocks or Statistical Areas with the mouse by pressing the shift key (or any other function key) and swiping over an area. Currently this can only be done by selecting them one by one. Selecting them by swiping over these with the cursor while holding a defined key would speed up the process of selecting tiles and creating arbitrary larger areas to investigate at a granular level.

**Comment by annikabock** [comment]
ok. hier ist erstmal alles klar soweit

**Comment by annikabock** [comment]
- beim klicken und halten der Command/Steuerungstaste wird ein Rechteck gezeichnet. Alle Teile, die sich innerhalb befinden werden angewählt.

- nicht implementiert bei Testbeds und bei Ansichten wo wir nur eine Einfachauswahl haben - also bei Solar, Energie und Mobility

**Comment by annikabock** [comment]
@imsk111 das habe ich wahrscheinlich missverständlich formuliert :) 
Genau bei denen - also bei Solar, Energie und Mobility - wird es implementiert. Nur beispielsweise bei der Ansicht der Testbeds nicht, da wir da sonst durcheinander kommen mit den Funktionalitäten.
