### ISSUE TITLE
some bugs/questions

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#396]
A few minor quirks:

1. removal of single line by pressing the "X" does not work reliably. Usually after the diagram has been started. Ist does not happen all the time but could be reproduced (Firefox, MacOS).

![Image](https://github.com/ANN-RADAR/ann-radar-prototype/assets/16405757/1e572173-2442-41d8-9a73-332267d72a91)

**Comment by imsk111** [comment]
Map does not show when creating and selecting model quarters and urban testbeds



![Image](https://github.com/ANN-RADAR/ann-radar-prototype/assets/16405757/32234145-781c-4b46-8875-5cf0463fbd56)

**Comment by imsk111** [comment]
some layers without pop up for details:
- schools
- suburban culture

**Comment by andreashelms** [comment]
``> some layers without pop up for details:
> 
> * schools
> * suburban culture

Popups are only shown for selected layers. I now added schools and culture to them:
````
            'buildingAndLiving',
            'socialInfrastructure',
            'streetTreeCadastre',
            'heatAtlas',
            'schools',
            'quarterCulture'
````
