### ISSUE TITLE
new bugs

### ISSUE THREAD

**Issue by imsk111** [ANN-RADAR/ann-radar-prototype#402]
Fehler bzw. Verbesserungen, die noch fehlen.

**Comment by imsk111** [comment]
Wert von Population = 0 nicht korrekt zugeordnet
Tabelle Stat Geb. 8007, Grafik Stat. Geb. 7002



![Image](https://github.com/ANN-RADAR/ann-radar-prototype/assets/16405757/90c592c4-bc79-4025-af3c-80fb5e50b4a9)

**Comment by imsk111** [comment]
Liste der Stat. Geb. im Diagramm stimmt nicht mit Tabelle überein. Die Gebiete sind in der Tabelle enthalten, man kann jedoch nicht nach unten scrollen. Die Gebiete sollten jedoch nicht enthalten sein, da sie nicht ausgewählt wurden.



![Image](https://github.com/ANN-RADAR/ann-radar-prototype/assets/16405757/45beeb5a-aaa6-433f-a6cc-5263bb1a9165)

**Comment by annikabock** [comment]
> Beim Abdeckungsgrad der Solarenergie könnten in der Legende noch % hinzugefügt werden (wie bei Renovierungspotential) ...
> 
> ![Image](https://user-images.githubusercontent.com/16405757/271587488-ca345240-bfee-4e0f-8b8e-89142c3edaae.png)

Die legende könnt ihr in der layers_config.json selbstständig hinzufügen, indem ihr dort die Unit setzt.
